import Footer from "@/components/commons/Footer";
import React from "react";

export const metadata = {
    title: "TalkNow - Discover the partners",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {

    return (
        <>
            {children}
            <Footer />
        </>
    );
}
